FROM phusion/baseimage:${BASEIMAGE_VERSION} as base

ARG MICROSCANNER_TOKEN

ENV MICROSCANNER_TOKEN="${MICROSCANNER_TOKEN}"

RUN if [ -z "${MICROSCANNER_TOKEN}" ]; then { echo "ERROR: MICROSCANNER_TOKEN not set"; exit 1; }; fi

COPY . /app/

# hadolint ignore=DL3008
RUN mv /etc/apt/sources.list /etc/apt/sources.list.original && \
    ln -s /app/sources.list /etc/apt/sources.list && \
    add-apt-repository ppa:apt-fast/stable && \
    apt-get update && \
    apt-get -y install --no-install-recommends apt-fast && \
    apt-fast -y upgrade && \
    apt-fast install --no-install-recommends -y \
      rsync \
      time \
      tzdata \
      wget \
      && \
    rm -fr /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/apt-fast/* && \
    chmod 755 /app/bin/*

RUN rm -fr /usr/share/man/* /usr/share/doc/*

RUN ln -s /app/bin/set_timezone.sh /etc/my_init.d/00_set_timezone.sh

RUN wget -nv https://github.com/jwilder/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz && \
    tar -C /app/bin -xzvf dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz && \
    rm dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz

RUN rm -fr /etc/service/sshd

ADD https://get.aquasec.com/microscanner .

RUN chmod 755 microscanner

RUN ./microscanner ${MICROSCANNER_TOKEN}

FROM scratch

COPY --from=base / /

ENV \
    APP_ENV="production" \
    APP_GID="1000" \
    APP_GROUP="app" \
    APP_HOSTNAME="example.com" \
    APP_UID="1000" \
    APP_USER="app" \
    CONTAINER_TIMEZONE="${CONTAINER_TIMEZONE}" \
    DEBIAN_FRONTEND="noninteractive" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8" \
    MICROSCANNER_TOKEN="" \
    PATH="/app/bin:$PATH"

WORKDIR /app

ENTRYPOINT ["/app/bin/entrypoint.sh"]

CMD ["/sbin/my_init"]
