FROM phusion/baseimage:${BASEIMAGE_VERSION} as base

COPY . /app/

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install --no-install-recommends -y \
      rsync \
      time \
      tzdata \
      wget && \
    apt-get clean && \
    rm -fr /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/apt-get/* && \
    chmod 755 /app/bin/* && \
    rm -fr /usr/share/man/* /usr/share/doc/* && \
    ln -s /app/bin/set_timezone.sh /etc/my_init.d/00_set_timezone.sh && \
    wget -nv https://github.com/jwilder/dockerize/releases/download/v${DOCKERIZE_VERSION}/dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz && \
    tar -C /app/bin -xzvf dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz && \
    rm dockerize-linux-amd64-v${DOCKERIZE_VERSION}.tar.gz && \
    rm -fr /etc/service/sshd

FROM scratch

COPY --from=base / /

ENV \
    APP_ENV="production" \
    APP_GID="1000" \
    APP_GROUP="app" \
    APP_HOSTNAME="example.com" \
    APP_UID="1000" \
    APP_USER="app" \
    CONTAINER_TIMEZONE="${CONTAINER_TIMEZONE}" \
    DEBIAN_FRONTEND="noninteractive" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8" \
    PATH="/app/bin:$PATH"

WORKDIR /app

ENTRYPOINT ["/app/bin/entrypoint.sh"]

CMD ["/sbin/my_init"]
