FROM gcr.io/planet-4-151612/openresty:${INFRA_VERSION}

LABEL authors="Raymond Walker <raymond.walker@greenpeace.org>"

ENV APP_ENV="production" \
    APP_HOSTNAME="k8s.p4.greenpeace.org" \
    PHP_ENABLED="true"

RUN rm -fr /app/source/public && \
    rm -f /app/bin/add_user.sh

COPY --chown=nginx:nginx . /app/
