# In this directory
#    - run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

# ============================================================================
#
# Beginning of build configuration
#

steps:
- id: 'configure-nginx-pagespeed'
  name: 'ubuntu'
  dir: './src/${PROJECT_ID}/nginx-pagespeed'
  args:
    - '/bin/sed'
    - '-i'
    - '-r'
    - '-e'
    - 's;FROM.*;FROM gcr.io/${PROJECT_ID}/ubuntu:${BRANCH_NAME};g'
    - 'Dockerfile'

- id: 'configure-nginx-php-exim'
  name: 'ubuntu'
  dir: './src/${PROJECT_ID}/wordpress'
  args:
    - '/bin/sed'
    - '-i'
    - '-r'
    - '-e'
    - 's;FROM.*;FROM gcr.io/${PROJECT_ID}/nginx-pagespeed:${BRANCH_NAME};g'
    - 'Dockerfile'

- id: 'configure-wordpress'
  name: 'ubuntu'
  dir: './src/${PROJECT_ID}/wordpress'
  args:
    - '/bin/sed'
    - '-i'
    - '-r'
    - '-e'
    - 's;FROM.*;FROM gcr.io/${PROJECT_ID}/nginx-php-exim:${BRANCH_NAME};g'
    - 'Dockerfile'

- id: 'configure-p4-onbuild'
  name: 'ubuntu'
  dir: './src/${PROJECT_ID}/p4-onbuild'
  args:
    - '/bin/sed'
    - '-i'
    - '-r'
    - '-e'
    - 's;FROM.*;FROM gcr.io/${PROJECT_ID}/wordpress:${BRANCH_NAME};g'
    - 'Dockerfile'

#
# End of configuration
#
# ============================================================================
#
# Begin service image builds
#

- id: 'ubuntu'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/ubuntu:${BRANCH_NAME}'
    - '--tag=gcr.io/${PROJECT_ID}/ubuntu:${SHORT_SHA}'
    - './src/${PROJECT_ID}/ubuntu'

- id: 'nginx-pagespeed'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/nginx-pagespeed:${BRANCH_NAME}'
    - '--tag=gcr.io/${PROJECT_ID}/nginx-pagespeed:${SHORT_SHA}'
    - './src/${PROJECT_ID}/nginx-pagespeed'
  waitFor:
    - 'configure-nginx-pagespeed'
    - 'ubuntu'

- id: 'nginx-php-exim'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/nginx-php-exim:${BRANCH_NAME}'
    - '--tag=gcr.io/${PROJECT_ID}/nginx-php-exim:${SHORT_SHA}'
    - './src/${PROJECT_ID}/nginx-php-exim'
  waitFor:
    - 'configure-nginx-php-exim'
    - 'nginx-pagespeed'

- id: 'wordpress'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/wordpress:${BRANCH_NAME}'
    - '--tag=gcr.io/${PROJECT_ID}/wordpress:${SHORT_SHA}'
    - './src/${PROJECT_ID}/wordpress'
  waitFor:
    - 'configure-wordpress'
    - 'nginx-php-exim'

- id: 'p4-onbuild'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/${PROJECT_ID}/p4-onbuild:${BRANCH_NAME}'
    - '--tag=gcr.io/${PROJECT_ID}/p4-onbuild:${SHORT_SHA}'
    - './src/${PROJECT_ID}/p4-onbuild'
  waitFor:
    - 'configure-p4-onbuild'
    - 'wordpress'

#
# End service image builds
#
# ============================================================================

images:
  - 'gcr.io/$PROJECT_ID/ubuntu:${BRANCH_NAME}'
  - 'gcr.io/$PROJECT_ID/ubuntu:${SHORT_SHA}'
  - 'gcr.io/$PROJECT_ID/nginx-pagespeed:${BRANCH_NAME}'
  - 'gcr.io/$PROJECT_ID/nginx-pagespeed:${SHORT_SHA}'
  - 'gcr.io/$PROJECT_ID/nginx-php-exim:${BRANCH_NAME}'
  - 'gcr.io/$PROJECT_ID/nginx-php-exim:${SHORT_SHA}'
  - 'gcr.io/$PROJECT_ID/wordpress:${BRANCH_NAME}'
  - 'gcr.io/$PROJECT_ID/wordpress:${SHORT_SHA}'
  - 'gcr.io/$PROJECT_ID/p4-onbuild:${BRANCH_NAME}'
  - 'gcr.io/$PROJECT_ID/p4-onbuild:${SHORT_SHA}'
