FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

LABEL authors="${MAINTAINER_NAME} <${MAINTAINER_EMAIL}>"

RUN apt-get update \
 && apt-get install -y --no-install-recommends exim4-daemon-light \
 && rm -Rf /tmp/* /var/tmp/* /var/lib/apt/lists/* \
 && rm -fr /usr/share/man/* /usr/share/doc/* /usr/share/locale/* \
 && touch /var/log/exim4/mainlog \
 && chown -R $(id -u Debian-exim):$(id -g Debian-exim) /var/log/exim4

EXPOSE 25

COPY . /app

ENV \
  EXIM_ADMIN_EMAIL="raymond.walker@greenpeace.org" \
  EXIM_DELIVERY_MODE="smarthost" \
  EXIM_MAIL_FROM="greenpeace.org" \
  EXIM_SMARTHOST_AUTH_PASSWORD="" \
  EXIM_SMARTHOST_AUTH_USERNAME="" \
  EXIM_SMARTHOST="smtp-relay.gmail.com::587"
