FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

RUN apt-get update \
 && apt-get install -y --no-install-recommends exim4-daemon-light \
 && rm -Rf /tmp/* /var/tmp/* /var/lib/apt/lists/* \
 && rm -fr /usr/share/man/* /usr/share/doc/* /usr/share/locale/*

EXPOSE 25

COPY . /app

ENV \
  EXIM_ADMIN_MAIL="raymond.walker@greenpeace.org" \
  EXIM_DELIVERY_MODE="smarthost" \
  EXIM_MAIL_FROM="greenpeace.org" \
  EXIM_SMARTHOST_AUTH_PASSWORD="" \
  EXIM_SMARTHOST_AUTH_USERNAME="" \
  EXIM_SMARTHOST="smtp.gmail.com::587"
