FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

ENTRYPOINT echo $@

ENV EXAMPLE_VAR="${EXAMPLE_VAR}"

CMD "World: ${EXAMPLE_VAR}"
