FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

MAINTAINER Ray Walker <hello@raywalker.it>

RUN wget --retry-connrefused --waitretry=1 -t 5 -O - https://download.newrelic.com/548C16BF.gpg | apt-key add - && \
    echo "deb http://apt.newrelic.com/debian/ newrelic non-free" > /etc/apt/sources.list.d/newrelic.list && \
    apt-get update && \
    apt-get -y --no-install-recommends install \
	    newrelic-php5 \
  		php \
  		php-cli \
  		php-curl \
  		php-gd \
  		php-imagick \
  		php-imap \
  		php-mcrypt \
  		php-xml \
  		php-xsl \
  		php-zip \
      php-fpm \
      php-intl \
      php-mbstring \
      php-memcache \
      php-memcached \
      php-mysql \
      php-recode \
      php-redis \
      php-soap \
      ssmtp \
      && \
    newrelic-install install && \
  	apt-get clean && \
    rm -Rf /tmp/* /var/tmp/* /var/lib/apt/lists/* && \
    rm -fr /usr/share/man/* /usr/share/doc/* /usr/share/locale/*

ENV \
    COMPOSER_HOME="/app/.composer" \
    DEFAULT_ADMIN_EMAIL="nobody@example.com" \
    DEFAULT_CHOWN_APP_DIR="false" \
    DEFAULT_NEWRELIC_APPNAME="${APPLICATION_NAME}" \
    DEFAULT_NEWRELIC_ENABLED="false" \
    DEFAULT_PHP_CLEAR_ENV="yes" \
    DEFAULT_PHP_DISABLE_FUNCTIONS="" \
    DEFAULT_PHP_HEALTH_CHECK_PATH="/health-check" \
    DEFAULT_PHP_HEALTH_CHECK_RESPONSE="ok" \
    DEFAULT_PHP_MAX_EXECUTION_TIME="300" \
    DEFAULT_PHP_MAX_INPUT_VARS="2000" \
    DEFAULT_PHP_MEMORY_LIMIT="128M" \
    DEFAULT_PHP_PROCESS_MANAGER_MAX_CHILDREN="6" \
    DEFAULT_PHP_PROCESS_MANAGER_MAX_REQUESTS="500" \
    DEFAULT_PHP_PROCESS_MANAGER_MAX_SPARE_SERVERS="3" \
    DEFAULT_PHP_PROCESS_MANAGER_MIN_SPARE_SERVERS="2" \
    DEFAULT_PHP_PROCESS_MANAGER_START_SERVERS="3" \
    DEFAULT_PHP_PROCESS_MANAGER="dynamic" \
    DEFAULT_PHP_SESSION_SAVE_HANDLER="files" \
    DEFAULT_PHP_SESSION_SAVE_PATH="/var/lib/php/sessions" \
    DEFAULT_UPLOAD_MAX_SIZE="50M" \
    DEFAULT_VIRTUAL_HOST="example.com" \
    SSMTP_MAIL_RELAY="smtp" \
    NEWRELIC_LICENSE="" \
    PHP_MAJOR_VERSION="${PHP_MAJOR_VERSION}"

EXPOSE 9000

COPY . /app/

RUN chmod 750 /app/bin/* && \
    sync && \
    /app/bin/init_php.sh && \
    /app/bin/php_install_composer.sh
