FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN wget --retry-connrefused --waitretry=1 -t 5 -O - https://download.newrelic.com/548C16BF.gpg | apt-key add - && \
    echo "deb http://apt.newrelic.com/debian/ newrelic non-free" > /etc/apt/sources.list.d/newrelic.list && \
    add-apt-repository ppa:ondrej/php && \
    apt-fast update && \
    apt-fast -y --no-install-recommends install \
      newrelic-php5 \
      php${PHP_MAJOR_VERSION} \
      php${PHP_MAJOR_VERSION}-cli \
      php${PHP_MAJOR_VERSION}-curl \
      php${PHP_MAJOR_VERSION}-fpm \
      php${PHP_MAJOR_VERSION}-gd \
      php${PHP_MAJOR_VERSION}-imagick \
      php${PHP_MAJOR_VERSION}-mbstring \
      php${PHP_MAJOR_VERSION}-mysql \
      php${PHP_MAJOR_VERSION}-recode \
      php${PHP_MAJOR_VERSION}-redis \
      php${PHP_MAJOR_VERSION}-xml \
      php${PHP_MAJOR_VERSION}-zip \
      ssmtp \
      && \
    newrelic-install install && \
    apt-fast clean && \
    rm -fr /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/apt-fast/*&& \
    rm -fr /usr/share/man/* /usr/share/doc/* /usr/share/locale/*

ENV ADMIN_EMAIL="nobody@example.com" \
    CHOWN_APP_DIR="false" \
    COMPOSER_HOME="/app/.composer" \
    COMPOSER_PROCESS_TIMEOUT="600" \
    COMPOSER_VERSION="${COMPOSER_VERSION}" \
    NEWRELIC_APPNAME="${APPLICATION_NAME}" \
    NEWRELIC_ENABLED="true" \
    NEWRELIC_LICENSE="" \
    PHP_CATCH_WORKERS_OUTPUT="yes" \
    PHP_CLEAR_ENV="yes" \
    PHP_DISABLE_FUNCTIONS="" \
    PHP_HEALTH_CHECK_PATH="/health-check" \
    PHP_HEALTH_CHECK_RESPONSE="ok" \
    PHP_MAJOR_VERSION="${PHP_MAJOR_VERSION}" \
    PHP_MAX_EXECUTION_TIME="300" \
    PHP_MAX_INPUT_VARS="2000" \
    PHP_MEMORY_LIMIT="256M" \
    PHP_PROCESS_MANAGER_MAX_CHILDREN="20" \
    PHP_PROCESS_MANAGER_MAX_REQUESTS="1000" \
    PHP_PROCESS_MANAGER_MAX_SPARE_SERVERS="4" \
    PHP_PROCESS_MANAGER_MIN_SPARE_SERVERS="3" \
    PHP_PROCESS_MANAGER_START_SERVERS="4" \
    PHP_PROCESS_MANAGER="dynamic" \
    PHP_SESSION_SAVE_HANDLER="files" \
    PHP_SESSION_SAVE_PATH="/var/lib/php/sessions" \
    SOURCE_PATH="${SOURCE_PATH}" \
    PUBLIC_PATH="${PUBLIC_PATH}" \
    SSMTP_MAIL_RELAY="smtp" \
    UPLOAD_MAX_SIZE="50M"

EXPOSE 9000

COPY . /app/

RUN chmod 750 /app/bin/* && \
    sync && \
    /app/bin/init_php.sh && \
    /app/bin/php_install_composer.sh
