FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

LABEL authors="${MAINTAINER_NAME} <${MAINTAINER_EMAIL}>"

RUN wget --retry-connrefused --waitretry=1 -t 5 -O - https://download.newrelic.com/548C16BF.gpg | apt-key add - && \
    echo "deb http://apt.newrelic.com/debian/ newrelic non-free" > /etc/apt/sources.list.d/newrelic.list && \
    apt-fast update && \
    apt-fast -y --no-install-recommends install \
	    newrelic-php5 \
  		php \
  		php-cli \
  		php-curl \
  		php-gd \
  		php-imagick \
  		php-imap \
  		php-mcrypt \
  		php-xml \
  		php-zip \
      php-fpm \
      php-intl \
      php-mbstring \
      php-mysql \
      php-recode \
      php-redis \
      ssmtp \
      && \
    newrelic-install install && \
    apt-fast clean && \
    rm -fr /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/apt-fast/*&& \
    rm -fr /usr/share/man/* /usr/share/doc/* /usr/share/locale/*

ENV ADMIN_EMAIL="nobody@example.com" \
    CHOWN_APP_DIR="false" \
    COMPOSER_HOME="/app/.composer" \
    COMPOSER_PROCESS_TIMEOUT="600" \
    COMPOSER_VERSION="${COMPOSER_VERSION}" \
    NEWRELIC_APPNAME="${APPLICATION_NAME}" \
    NEWRELIC_ENABLED="true" \
    NEWRELIC_LICENSE="" \
    PHP_CLEAR_ENV="yes" \
    PHP_DISABLE_FUNCTIONS="" \
    PHP_HEALTH_CHECK_PATH="/health-check" \
    PHP_HEALTH_CHECK_RESPONSE="ok" \
    PHP_MAJOR_VERSION="${PHP_MAJOR_VERSION}" \
    PHP_MAX_EXECUTION_TIME="300" \
    PHP_MAX_INPUT_VARS="2000" \
    PHP_MEMORY_LIMIT="128M" \
    PHP_PROCESS_MANAGER_MAX_CHILDREN="10" \
    PHP_PROCESS_MANAGER_MAX_REQUESTS="10000" \
    PHP_PROCESS_MANAGER_MAX_SPARE_SERVERS="3" \
    PHP_PROCESS_MANAGER_MIN_SPARE_SERVERS="2" \
    PHP_PROCESS_MANAGER_START_SERVERS="3" \
    PHP_PROCESS_MANAGER="dynamic" \
    PHP_SESSION_SAVE_HANDLER="files" \
    PHP_SESSION_SAVE_PATH="/var/lib/php/sessions" \
    SOURCE_PATH="${SOURCE_PATH}" \
    PUBLIC_PATH="${PUBLIC_PATH}" \
    SSMTP_MAIL_RELAY="smtp" \
    UPLOAD_MAX_SIZE="50M"

EXPOSE 9000

COPY . /app/

RUN chmod 750 /app/bin/* && \
    sync && \
    /app/bin/init_php.sh && \
    /app/bin/php_install_composer.sh
