FROM gcr.io/planet-4-151612/circleci-base:develop

LABEL authors="${MAINTAINER_NAME} <${MAINTAINER_EMAIL}>"

COPY --chown=circleci:circleci . /home/circleci/

RUN chmod 755 /home/circleci/*.sh && \
    helm init --client-only && \
    helm repo add p4-helm-charts https://p4-helm-charts.storage.googleapis.com
