---
steps:
  - id: 'hello-world'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/hello-world:${_BUILD_TAG}'
      - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/hello-world:${_BUILD_NUM}'
      - '--tag=${_BUILD_NAMESPACE}/${_GOOGLE_PROJECT_ID}/hello-world:${_REVISION_TAG}'
      - '.'

images:
  - '${_BUILD_NAMESPACE}/$PROJECT_ID/hello-world:${_BUILD_TAG}'
  - '${_BUILD_NAMESPACE}/$PROJECT_ID/hello-world:${_BUILD_NUM}'
  - '${_BUILD_NAMESPACE}/$PROJECT_ID/hello-world:${_REVISION_TAG}'
