#!/bin/bash
set -euf

source /app/bin/colours.sh
source /app/bin/env.sh

_good "Starting service: php-fpm${PHP_MAJOR_VERSION} ..."

# start PHP
exec php-fpm${PHP_MAJOR_VERSION} -c /etc/php/${PHP_MAJOR_VERSION}/fpm
