FROM ${IMAGE_NAMESPACE}/${BATS_PROJECT_ID}/handbook:${IMAGE_TAG}

ENV \
  APP_HOSTNAME="${APP_HOSTNAME}" \
  GIT_SOURCE="${GIT_SOURCE}" \
  GIT_REF="${GIT_BRANCH}" \
  WP_TITLE="${WP_TITLE}"

RUN cd .. && \
  git clone "${GIT_SOURCE}" source && \
  cd source && \
  git checkout "${GIT_BRANCH}" && \
  /app/bin/composer.phar --profile -vv install && \
  /app/bin/composer.phar clearcache
