#!/bin/bash
set -eu

# =============================================================================
# 	PHP-FPM
# =============================================================================

# Ubuntu xenial php for some reason doesn't create /run/php,
# where it expects socket files to live
mkdir -p /run/php
chown -R "${APP_USER}" /run/php

touch "/var/log/php${PHP_MAJOR_VERSION}-fpm.log"
touch "/var/log/php${PHP_MAJOR_VERSION}-fpm.${PHP_POOL_NAME}.error.log"

chown -R "${APP_USER}" "/var/log/php${PHP_MAJOR_VERSION}-fpm.log"
chown -R "${APP_USER}" "/var/log/php${PHP_MAJOR_VERSION}-fpm.${PHP_POOL_NAME}.error.log"

_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "clear_env:")" "${PHP_CLEAR_ENV}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "disable_functions:")" "${PHP_DISABLE_FUNCTIONS}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "group:")" "${APP_GROUP}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "max_execution_time:")" "${PHP_MAX_EXECUTION_TIME}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "max_input_vars:")" "${PHP_MAX_INPUT_VARS}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "memory_limit:")" "${PHP_MEMORY_LIMIT}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "pm.max_children:")" "${PHP_PROCESS_MANAGER_MAX_CHILDREN}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "pm.max_requests:")" "${PHP_PROCESS_MANAGER_MAX_REQUESTS}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "pm.max_spare_servers:")" "${PHP_PROCESS_MANAGER_MAX_SPARE_SERVERS}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "pm.min_spare_servers:")" "${PHP_PROCESS_MANAGER_MIN_SPARE_SERVERS}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "pm.start_servers:")" "${PHP_PROCESS_MANAGER_START_SERVERS}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "pool name:")" "${PHP_POOL_NAME}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "post_max_size:")" "${UPLOAD_MAX_SIZE}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "session.save_handler:")" "${PHP_SESSION_SAVE_HANDLER}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "session.save_path:")" "${PHP_SESSION_SAVE_PATH}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "upload_max_filesize:")" "${UPLOAD_MAX_SIZE}"
_good "$(printf "%-10s " "php:")" "$(printf "%-22s" "user:")" "${APP_USER}"

# newrelic
php_configure_newrelic.sh

_title "Starting service: php-fpm $(php --version | head -n 1 | cut -d " " -f 2)"

# start PHP
dockerize \
  -template "/app/templates/etc/php/fpm/pool.d/www.conf.tmpl:/etc/php/${PHP_MAJOR_VERSION}/fpm/pool.d/www.conf" \
  -template "/app/templates/etc/php/fpm/conf.d/20-newrelic.ini.tmpl:/etc/php/${PHP_MAJOR_VERSION}/fpm/conf.d/20-newrelic.ini" \
  -template /app/templates/etc/ssmtp/ssmtp.conf.tmpl:/etc/ssmtp/ssmtp.conf

exec dockerize \
  -stdout "/var/log/php${PHP_MAJOR_VERSION}-fpm.log" \
  -stderr "/var/log/php${PHP_MAJOR_VERSION}-fpm.${PHP_POOL_NAME}.error.log" \
  "php-fpm${PHP_MAJOR_VERSION}" -c "/etc/php/${PHP_MAJOR_VERSION}/fpm"
