FROM gcr.io/${PROJECT_ID}/p4-onbuild:${IMAGE_TAG:-develop}

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

ENV WP_TITLE="Greenpeace International - Development Site"
ENV APP_HOSTNAME "test.planet4.dev"
ENV SSL_ENABLED "false"

ENV COMPOSER="composer-dev.json"
