FROM ${IMAGE_NAMESPACE}/${BATS_PROJECT_ID}/p4-onbuild:${IMAGE_TAG}

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

ENV WP_TITLE="GPI - Testing Site"
ENV APP_HOSTNAME "${APP_HOSTNAME}"
ENV SSL_ENABLED "false"

ENV COMPOSER="${COMPOSER}"
