FROM gcr.io/planet-4-151612/p4-onbuild

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

ENV COMPOSER="composer-dev.json"
ENV WP_TITLE="Greenpeace International"
ENV APP_HOSTNAME "test.planet4.dev"
ENV SSL_ENABLED "false"
