FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/php-fpm:${SOURCE_VERSION}

RUN apt-get update && \
    apt-fast install -y --no-install-recommends \
      git \
      jq \
      mysql-client \
      unzip \
      && \
    apt-get clean && \
    rm -Rf /tmp/* /var/tmp/* /var/lib/apt/lists/* && \
    curl --retry 5 -o /app/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    ln -s /app/bin/wp.sh /app/bin/wp && \
    php /app/bin/composer.phar -vv global require hirak/prestissimo && \
    mkdir -p "${SOURCE_PATH}"

COPY . /app/

WORKDIR ${SOURCE_PATH}

ENV \
    APP_HOSTPATH="" \
    CLOUDFLARE_API_KEY="" \
    DELETE_EXISTING_FILES="false" \
    GIT_REF="main" \
    GIT_SOURCE="${GIT_SOURCE}" \
    INSTALL_WORDPRESS="true" \
    MERGE_REF="" \
    MERGE_SOURCE="" \
    OVERWRITE_EXISTING_FILES="false" \
    PHP_CLEAR_ENV="yes" \
    SMARTSHEET_API_KEY="" \
    WP_ADMIN_EMAIL="${MAINTAINER_EMAIL}" \
    WP_ADMIN_NAME="" \
    WP_ADMIN_PASS="" \
    WP_ADMIN_USER="" \
    WP_AUTH_KEY="" \
    WP_AUTH_SALT="" \
    WP_AUTO_UPDATE_CORE="false" \
    WP_AUTOMATIC_UPDATER_DISABLED="true" \
    WP_BAKE="false" \
    WP_CLI_CACHE_DIR="/app/.wp-cli/cache" \
    WP_CLI_DISABLE_AUTO_CHECK_UPDATE="true" \
    WP_DB_CHARSET="utf8" \
    WP_DB_COLLATION="" \
    WP_DB_HOST="db" \
    WP_DB_NAME="" \
    WP_DB_PASS="" \
    WP_DB_PORT="3306" \
    WP_DB_PREFIX="wp_" \
    WP_DB_USER="" \
    WP_DESCRIPTION="Greenpeace" \
    WP_DISALLOW_FILE_MODS="true" \
    WP_DOWNLOAD_FLAGS="--skip-content" \
    WP_EXTRA_CONFIG="" \
    WP_FORCE_SSL_ADMIN="true" \
    WP_HOSTNAME="" \
    WP_LOCALE="en_AU" \
    WP_LOGGED_IN_KEY="" \
    WP_LOGGED_IN_SALT="" \
    WP_NONCE_KEY="" \
    WP_NONCE_SALT="" \
    WP_REDIS_ENABLED="false" \
    WP_REDIS_HOST="redis" \
    WP_REDIS_PORT="6379" \
    WP_REDIS_DB="0" \
    WP_REDIS_DEFAULT_EXPIRE_SECONDS="86400" \
    WP_REWRITE_STRUCTURE="/%category%/%post_id%/%postname%/" \
    WP_SECURE_AUTH_KEY="" \
    WP_SECURE_AUTH_SALT="" \
    WP_SET_OPTIONS_ON_BOOT="true" \
    WP_SENTRY_DSN="" \
    WP_SENTRY_ERROR_TYPES="E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED" \
    WP_SITE_HOME="" \
    WP_SITE_PROTOCOL="https" \
    WP_SITE_URL="" \
    WP_STATELESS_MEDIA_BUCKET="" \
    WP_STATELESS_MEDIA_ENABLED="" \
    WP_STATELESS_MEDIA_JSON_KEY="" \
    WP_STATELESS_MEDIA_KEY_FILE_PATH="" \
    WP_STATELESS_MEDIA_MODE="stateless" \
    WP_STATELESS_MEDIA_ROOT_DIR="" \
    WP_STATELESS_MEDIA_SERVICE_ACCOUNT="" \
    WP_THEME="planet4-master-theme" \
    WP_TITLE="Greenpeace" \
    WP_VERSION="latest"
