FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/php-fpm:${SOURCE_VERSION}

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

RUN apt-get update && \
    apt-get install -y --no-install-recommends rsync git mysql-client && \
    apt-get clean && \
    rm -Rf /tmp/* /var/tmp/* /var/lib/apt/lists/* && \
    curl --retry 5 -o /app/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    ln -s /app/bin/wp.sh /app/bin/wp

COPY . /app/

ENV \
    INSTALL_WORDPRESS="true" \
    OVERWRITE_FILES="false" \
    PHP_CLEAR_ENV="no" \
    WP_ADMIN_EMAIL="" \
    WP_ADMIN_NAME="" \
    WP_ADMIN_PASS="" \
    WP_ADMIN_USER="" \
    WP_AUTH_KEY="" \
    WP_AUTH_SALT="" \
    WP_AUTO_UPDATE_CORE="minor" \
    WP_BAKE="false" \
    WP_CLI_CACHE_DIR="/app/.wp-cli/cache" \
    WP_CLI_DISABLE_AUTO_CHECK_UPDATE="true" \
    WP_DB_CHARSET="utf8" \
    WP_DB_COLLATION="" \
    WP_DB_HOST="db" \
    WP_DB_NAME="" \
    WP_DB_PASS="" \
    WP_DB_PORT="3306" \
    WP_DB_PREFIX="wp_" \
    WP_DB_USER="" \
    WP_DEFAULT_CONTENT="true" \
    WP_EXTRA_CONFIG="" \
    WP_FORCE_SSL_ADMIN="false" \
    WP_HOSTNAME="" \
    WP_LOCALE="en_AU" \
    WP_LOGGED_IN_KEY="" \
    WP_LOGGED_IN_SALT="" \
    WP_NONCE_KEY="" \
    WP_NONCE_SALT="" \
    WP_REDIS_ENABLED="false" \
    WP_REDIS_HOST="redis" \
    WP_REDIS_PORT="6379" \
    WP_REDIS_DB="0" \
    WP_REWRITE_STRUCTURE="/%category%/%post_id%/%postname%/" \
    WP_SECURE_AUTH_KEY="" \
    WP_SECURE_AUTH_SALT="" \
    WP_SET_OPTIONS_ON_BOOT="true" \
    WP_SITE_HOME="" \
    WP_SITE_PROTOCOL="https" \
    WP_SITE_URL="" \
    WP_STATELESS_MEDIA_BUCKET="docker.p4.greenpeace.org" \
    WP_STATELESS_MEDIA_ENABLED="false" \
    WP_STATELESS_MEDIA_JSON_KEY="" \
    WP_STATELESS_MEDIA_KEY_FILE_PATH="" \
    WP_STATELESS_MEDIA_MODE="stateless" \
    WP_STATELESS_MEDIA_ROOT_DIR="${BRANCH_NAME}" \
    WP_STATELESS_MEDIA_SERVICE_ACCOUNT="stateless-docker-p4-greenp-111@planet-4-151612.iam.gserviceaccount.com" \
    WP_TITLE="${APPLICATION_NAME}" \
    WP_VERSION="latest"
