FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

MAINTAINER Raymond Walker <raymond.walker@greenpeace.org>

EXPOSE 80
EXPOSE 443

ENV \
    APP_GID="1000" \
    APP_GROUP="nginx" \
    APP_UID="1000" \
    APP_USER="nginx" \
    NGX_PAGESPEED_RELEASE="${NGX_PAGESPEED_RELEASE}" \
    NGX_PAGESPEED_VERSION="${NGX_PAGESPEED_VERSION}" \
    OPENRESTY_VERSION="${OPENRESTY_VERSION}" \
    OPENSSL_VERSION="${OPENSSL_VERSION}"

COPY . /app/

RUN set -ex && \
    groupadd -g "${APP_GID}" "${APP_GROUP}" && \
    useradd -r -s /usr/sbin/nologin "${APP_USER}" -u "${APP_UID}" -g "${APP_GID}" && \
    apt-get update && \
    apt-get -y --no-install-recommends install \
      autoconf \
      automake \
      build-essential \
      libgd2-xpm-dev \
      libgeoip-dev \
      libgoogle-perftools-dev \
      libpcre3-dev \
      libperl-dev \
      libtool \
      libxml2-dev \
      libxslt1-dev \
      zlib1g-dev \
      & \
    wget --retry-connrefused --waitretry=1 -t 5 --progress=bar -O - "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz" | tar xzf - -C /tmp & \
    wget --retry-connrefused --waitretry=1 -t 5 --progress=bar -O - "https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz" | tar zxf - -C /tmp & \
    wget --retry-connrefused --waitretry=1 -t 5 --progress=bar -O - "https://github.com/pagespeed/ngx_pagespeed/archive/${NGX_PAGESPEED_VERSION}-${NGX_PAGESPEED_RELEASE}.tar.gz" | tar zxf - -C /tmp && \
    PSOL_URL="$(cat "/tmp/ngx_pagespeed-${NGX_PAGESPEED_VERSION}-${NGX_PAGESPEED_RELEASE}/PSOL_BINARY_URL")" && \
    if [ "$(uname -m)" = x86_64 ]; then PSOL_BIT_SIZE_NAME="x64"; else PSOL_BIT_SIZE_NAME="ia32"; fi && \
    wget --retry-connrefused --waitretry=1 -t 5 --progress=bar -O - "$(echo $PSOL_URL | sed "s/\$BIT_SIZE_NAME/$PSOL_BIT_SIZE_NAME/g")" | tar zxf - -C "/tmp/ngx_pagespeed-${NGX_PAGESPEED_VERSION}-${NGX_PAGESPEED_RELEASE}" & \
    procs=$(cat /proc/cpuinfo |grep processor | wc -l) && \
    mkdir -p /var/log/nginx /var/cache/nginx && \
    wait && \
    cd "/tmp/openresty-${OPENRESTY_VERSION}" && \
    ./configure \
      -j${procs} \
  		--prefix=/etc/nginx  \
  		--sbin-path=/usr/sbin/nginx  \
  		--conf-path=/etc/nginx/nginx.conf  \
  		--error-log-path=/var/log/nginx/error.log \
  		--http-log-path=/var/log/nginx/access.log \
  		--pid-path=/var/run/nginx.pid \
  		--lock-path=/var/run/nginx.lock \
  		--http-client-body-temp-path=/var/cache/nginx/client_temp \
  		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
  		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp  \
  		--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp  \
  		--http-scgi-temp-path=/var/cache/nginx/scgi_temp  \
  		--user="${APP_USER}"  \
  		--group="${APP_USER}"  \
  		--with-http_ssl_module  \
  		--with-http_realip_module  \
  		--with-http_addition_module  \
  		--with-http_sub_module  \
  		--with-http_dav_module  \
  		--with-http_flv_module  \
  		--with-http_mp4_module  \
  		--with-http_gunzip_module  \
  		--with-http_gzip_static_module  \
  		--with-http_secure_link_module \
  		--with-http_stub_status_module  \
  		--with-http_auth_request_module  \
  		--without-http_autoindex_module \
      --without-http_encrypted_session_module \
  		--with-threads  \
  		--with-stream  \
  		--with-stream_ssl_module  \
  		--with-mail  \
  		--with-mail_ssl_module  \
  		--with-file-aio  \
  		--with-http_v2_module \
  		--with-cc-opt='-g -O2 -fstack-protector-strong --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2'  \
  		--with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed' \
  		--with-ipv6 \
  		--with-pcre-jit \
  		--with-openssl=/tmp/openssl-${OPENSSL_VERSION} \
  		--add-module=/tmp/ngx_pagespeed-${NGX_PAGESPEED_VERSION}-${NGX_PAGESPEED_RELEASE}  && \
  	make -j${procs} install && \
  	apt-get purge -yqq \
      autoconf \
      automake \
      build-essential \
      libgd2-xpm-dev \
      libgeoip-dev \
      libgoogle-perftools-dev \
      libpcre3-dev \
      libperl-dev \
      libtool \
      libxml2-dev \
      libxslt1-dev \
      zlib1g-dev \
      && \
  	apt-get autoremove -yqq && \
  	rm -Rf /tmp/* /var/tmp/* /var/lib/apt/lists/* && \
    rm -fr /usr/share/man/* /usr/share/doc/* /usr/share/locale/* && \
    mkdir -p /etc/nginx/ssl /app/www && \
    echo "$(nginx -V 2>&1)" > /app/www/index.html

ENV \
    CLOUDFLARE_ENABLED="false" \
    DEFAULT_CHOWN_APP_DIR="false" \
    DEFAULT_OPENRESTY_FASTCGI_BACKEND="php-fpm:9000" \
    DEFAULT_OPENRESTY_KEEPALIVE_TIMEOUT="30" \
    DEFAULT_OPENRESTY_MAX_WORKER_PROCESSES="8" \
    DEFAULT_OPENRESTY_SENDFILE="on" \
    DEFAULT_PAGESPEED_DISABLE_FILTERS="" \
    DEFAULT_PAGESPEED_REBEACON_KEY="uwuudeL7iedoo7Meengi" \
    DEFAULT_PAGESPEED_REWRITE_LEVEL="CoreFilters" \
    DEFAULT_REDIS_FASTCGI_CACHE_SERVER="redis:6379" \
    DEFAULT_UPLOAD_MAX_SIZE="50M" \
    PAGESPEED_ENABLED="true" \
    PHP_ENABLED="false" \
    REDIS_FASTCGI_CACHE_ENABLED="false" \
    SSL_ENABLED="false"
