FROM ${BUILD_NAMESPACE}/${GOOGLE_PROJECT_ID}/ubuntu:${SOURCE_VERSION}

LABEL authors="${MAINTAINER_NAME} <${MAINTAINER_EMAIL}>"

EXPOSE 80
EXPOSE 443

ENV \
    APP_GID="1000" \
    APP_GROUP="nginx" \
    APP_UID="1000" \
    APP_USER="nginx" \
    APP_HOSTPATH="international" \
    CHOWN_APP_DIR="false" \
    CLOUDFLARE_ENABLED="false" \
    NGX_PAGESPEED_RELEASE="${NGX_PAGESPEED_RELEASE}" \
    NGX_PAGESPEED_VERSION="${NGX_PAGESPEED_VERSION}" \
    OPENRESTY_FASTCGI_BACKEND="php-fpm:9000" \
    OPENRESTY_KEEPALIVE_TIMEOUT="30" \
    OPENRESTY_MAX_WORKER_PROCESSES="8" \
    OPENRESTY_SENDFILE="on" \
    OPENRESTY_SOURCE="${OPENRESTY_SOURCE}" \
    OPENRESTY_VERSION="${OPENRESTY_VERSION}" \
    PAGESPEED_ADMIN_PATH="/_pagespeed_admin" \
    PAGESPEED_DISABLE_FILTERS="" \
    PAGESPEED_ENABLED="false" \
    PAGESPEED_REBEACON_KEY="uwuudeL7iedoo7Meengi" \
    PAGESPEED_REDIS_SERVER="redis:6379" \
    PAGESPEED_REWRITE_LEVEL="CoreFilters" \
    PAGESPEED_STATISTICS_ENABLED="off" \
    PHP_ENABLED="false" \
    REDIS_FASTCGI_CACHE_ENABLED="false" \
    REDIS_FASTCGI_CACHE_SERVER="redis:6379" \
    PUBLIC_PATH="${PUBLIC_PATH}" \
    SSL_ENABLED="false" \
    UPLOAD_MAX_SIZE="50M"

COPY ./bin/install_openresty.sh /app/bin/install_openresty.sh

RUN groupadd -g "${APP_GID}" "${APP_GROUP}" && \
    useradd -r -s /usr/sbin/nologin "${APP_USER}" -u "${APP_UID}" -g "${APP_GID}" && \
    time sh -c "/app/bin/install_openresty.sh" && \
    rm -fr /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/apt-fast/* && \
    rm -fr /usr/share/man/* /usr/share/doc/* /usr/share/locale/* && \
    mkdir -p /etc/nginx/ssl "${PUBLIC_PATH}" && \
    echo "$(nginx -V 2>&1)" > "${PUBLIC_PATH}/index.html" && \
    echo "TEST-DATA-ONLY" >> "${PUBLIC_PATH}/index.html"

COPY . /app/
